# Load Libraries

In [1]:
import os
import warnings
import logging
import sys
import pickle
import numpy as np
import pandas as pd
import geopandas as gpd
import dotenv

# Load environment variables from .env file
dotenv.load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)

# Suppress warnings
warnings.filterwarnings("ignore")

# Set display options for pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_colwidth', None)

# Load Data

In [2]:
# Define file paths using environment variables
DATA_FOLDER_PATH = os.getenv('DATA_FOLDER_PATH')
DATA_NAME = os.getenv('DATA_NAME')
GEOINFO_NAME = os.getenv('GEOINFO_NAME')

if not DATA_FOLDER_PATH or not DATA_NAME or not GEOINFO_NAME:
    logging.error("Environment variables DATA_FOLDER_PATH, DATA_NAME, or GEOINFO_NAME are not set.")
    sys.exit(1)

# Construct full file paths
DATA_PATH = os.path.join(DATA_FOLDER_PATH, DATA_NAME + '.parquet')
GEOINFO_PATH = os.path.join(DATA_FOLDER_PATH, GEOINFO_NAME + '.geojson')

# Load datasets
try:
    # Read Parquet file with pandas
    data = pd.read_parquet(DATA_PATH)
    logging.info(f"Data loaded successfully from {DATA_PATH}")
except Exception as e:
    logging.error(f"Error loading data from {DATA_PATH}: {e}")
    sys.exit(1)

try:
    # Read GeoJSON file with geopandas    
    geoinfo = gpd.read_file(GEOINFO_PATH)
    logging.info(f"Geoinfo loaded successfully from {GEOINFO_PATH}")
except Exception as e:
    logging.error(f"Error loading geoinfo from {GEOINFO_PATH}: {e}")
    sys.exit(1)

INFO:root:Data loaded successfully from C:/Users/Pooya/Dropbox/IRIMO/Export/Iran_Data_1951_2025\IRIMO_Data.parquet
INFO:root:Geoinfo loaded successfully from C:/Users/Pooya/Dropbox/IRIMO/Export/Iran_Data_1951_2025\IRIMO_GeoInfo.geojson

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4928061 entries, 0 to 4928060
Data columns (total 55 columns):
 #   Column             Dtype
---  ------             -----
 0   station_id         category
 1   station_name       category
 2   region_id          category
 3   region_name        category
 4   lat                float64
 5   lon                float64
 6   station_elevation  float64
 7   date               datetime64[ns]
 8   ff_max             float64
 9   dd_max             float64
 10  ffm                float64
 11  tmax               float64
 12  tmin               float64
 13  tm                 float64
 14  pm                 float64
 15  p0m                float64
 16  ewm                float64
 17  rrr24              float64
 18  nm                 float64
 19  nmax               float64
 20  essmax             float64
 21  umax               float64
 22  umin               float64
 23  um                 float64
 24  sshn               float64
 25  radglo24           float64
 26  evt                float64
 27  td_m               float64
 28  twet_m             float64
 29  ss24               float64
 30  tsoil_m            float64
 31  tsoil_min          float64
 32  ewsm               float64
 33  vvmin              float64
 34  ff_gust_max        float64
 35  dd_gust_max        float64
 36  pmin               float64
 37  rrrtmax            float64
 38  nsn                float64
 39  nrasn              float64
 40  ngf                float64
 41  nshra              float64
 42  ndu                float64
 43  nbdu               float64
 44  ness               float64
 45  hrel_03            float64
 46  hrel_09            float64
 47  hrel_15            float64
 48  nra                float64
 49  nhz                float64
 50  pmax               float64
 51  p0max              float64
 52  p0min              float64
 53  dj21               float64
 54  dj18               float64
dtypes: category(4), datetime64[ns](1), float64(50)
memory usage: 1.9 GB

In [4]:
data.region_name.unique().tolist()

['Airforce',
 'Alborz',
 'Ardebil',
 'Azarbayjan-E-Gharbi',
 'Azarbayjan-E-Sharghi',
 'Bushehr',
 'Chaharmahal Va Bakhtiari',
 'Esfahan',
 'Fars',
 'Gilan',
 'Golestan',
 'Hamedan',
 'Hormozgan',
 'Ilam',
 'Kerman',
 'Kermanshah',
 'Khohgiluyeh Va Boyerahmad',
 'Khorasan Razavi',
 'Khuzestan',
 'Kordestan',
 'Lorestan',
 'Markazi',
 'Mazandaran',
 'North Khorasan',
 'Qazvin',
 'Qom',
 'Semnan',
 'Sistan Va Baluchestan',
 'South Khorasan',
 'Tehran',
 'Yazd',
 'Zanjan']

# Filter Data

In [5]:
# selected_regions = ["Khorasan Razavi", "South Khorasan", "North Khorasan"]

selected_columns = [
    'station_id',
    'station_name',
    'region_id',
    'region_name',
    'lat',
    'lon',
    'station_elevation',
    'date',
    'tmax',
    'tmin',
    'tm',
    'umax',
    'umin',
    'um',
    'ffm',
    'sshn',
    'rrr24',
    'pm',
    'p0m',
    'ewm',
    'radglo24',
    'evt',
    'td_m',
    'twet_m',
    'tsoil_m',
    'ewsm',
]

# df = data.filter(items=selected_columns).query("region_name in @selected_regions").copy()
df = data.filter(items=selected_columns).copy()

def remove_unused_if_cat(s):
    if pd.api.types.is_categorical_dtype(s.dtype):
        return s.cat.remove_unused_categories()
    else:
        return s

df = df.apply(remove_unused_if_cat)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4928061 entries, 0 to 4928060
Data columns (total 26 columns):
 #   Column             Dtype
---  ------             -----
 0   station_id         category
 1   station_name       category
 2   region_id          category
 3   region_name        category
 4   lat                float64
 5   lon                float64
 6   station_elevation  float64
 7   date               datetime64[ns]
 8   tmax               float64
 9   tmin               float64
 10  tm                 float64
 11  umax               float64
 12  umin               float64
 13  um                 float64
 14  ffm                float64
 15  sshn               float64
 16  rrr24              float64
 17  pm                 float64
 18  p0m                float64
 19  ewm                float64
 20  radglo24           float64
 21  evt                float64
 22  td_m               float64
 23  twet_m             float64
 24  tsoil_m            float64
 25  ewsm               float64
dtypes: category(4), datetime64[ns](1), float64(21)
memory usage: 855.4 MB

# Filter Data

In [7]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4927527 entries, 0 to 4927526
Data columns (total 26 columns):
 #   Column             Dtype
---  ------             -----
 0   station_id         category
 1   station_name       category
 2   region_id          category
 3   region_name        category
 4   lat                float64
 5   lon                float64
 6   station_elevation  float64
 7   date               datetime64[ns]
 8   tmax               float64
 9   tmin               float64
 10  tm                 float64
 11  umax               float64
 12  umin               float64
 13  um                 float64
 14  ffm                float64
 15  sshn               float64
 16  rrr24              float64
 17  pm                 float64
 18  p0m                float64
 19  ewm                float64
 20  radglo24           float64
 21  evt                float64
 22  td_m               float64
 23  twet_m             float64
 24  tsoil_m            float64
 25  ewsm               float64
dtypes: category(4), datetime64[ns](1), float64(21)
memory usage: 855.3 MB

# Data Quality Control

In [9]:
def data_quality_control(
    df, 
    required_vars = ['tm']
):
    if 'tm' in required_vars and 'tm' in df.columns:
        df.loc[(df['tm'] < -60) | (df['tm'] > 80), 'tm'] = np.nan
    if 'tmax' in required_vars and 'tmax' in df.columns:
        df.loc[(df['tmax'] < -60) | (df['tmax'] > 80), 'tmax'] = np.nan
    if 'tmin' in required_vars and 'tmin' in df.columns:
        df.loc[(df['tmin'] < -60) | (df['tmin'] > 80), 'tmin'] = np.nan
    if 'um' in required_vars and 'um' in df.columns:
        df.loc[(df['um'] < 0) | (df['um'] > 100), 'um'] = np.nan
    if 'umax' in required_vars and 'umax' in df.columns:
        df.loc[(df['umax'] < 0) | (df['umax'] > 100), 'umax'] = np.nan
    if 'umin' in required_vars and 'umin' in df.columns:
        df.loc[(df['umin'] < 0) | (df['umin'] > 100), 'umin'] = np.nan
    if 'ffm' in required_vars and 'ffm' in df.columns:
        df.loc[(df['ffm'] < 0) | (df['ffm'] > 50), 'ffm'] = np.nan
    if 'sshn' in required_vars and 'sshn' in df.columns:
        df.loc[(df['sshn'] < 0) | (df['sshn'] > 24), 'sshn'] = np.nan
    if 'rrr24' in required_vars and 'rrr24' in df.columns:
        df.loc[(df['rrr24'] < 0) | (df['rrr24'] > 1000), 'rrr24'] = np.nan
    return df


df = data_quality_control(
    df=df, 
    required_vars=['tm', 'tmax', 'tmin', 'um', 'umin', 'umax', 'ffm', 'sshn', 'rrr24']
)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4927527 entries, 0 to 4927526
Data columns (total 26 columns):
 #   Column             Dtype
---  ------             -----
 0   station_id         category
 1   station_name       category
 2   region_id          category
 3   region_name        category
 4   lat                float64
 5   lon                float64
 6   station_elevation  float64
 7   date               datetime64[ns]
 8   tmax               float64
 9   tmin               float64
 10  tm                 float64
 11  umax               float64
 12  umin               float64
 13  um                 float64
 14  ffm                float64
 15  sshn               float64
 16  rrr24              float64
 17  pm                 float64
 18  p0m                float64
 19  ewm                float64
 20  radglo24           float64
 21  evt                float64
 22  td_m               float64
 23  twet_m             float64
 24  tsoil_m            float64
 25  ewsm               float64
dtypes: category(4), datetime64[ns](1), float64(21)
memory usage: 855.3 MB

# Fill Missing Dates

In [11]:
d = df[['region_id', 'region_name', 'station_name', 'station_id', 'lat', 'lon', 'station_elevation']].drop_duplicates().reset_index(drop=True)
d[d.duplicated(subset=['region_name', 'station_name'], keep=False)]

,region_id,region_name,station_name,station_id,lat,lon,station_elevation
359,OIKK,Kerman,Golbaf,19680,29.85,57.73,1665.00
360,OIKK,Kerman,Golbaf,99583,29.85,57.73,1665.00
519,OICK,Lorestan,Rymaleh,19124,33.64,48.40,1650.00
520,OICK,Lorestan,Rymaleh,99471,33.64,48.40,1650.00
582,OIMN,North Khorasan,Shirvan,18203,37.38,57.92,1187.00
583,OIMN,North Khorasan,Shirvan,99270,37.43,57.83,1051.00
630,OIIS,Semnan,Shahmirzad,90250,35.78,53.37,1960.00
631,OIIS,Semnan,Shahmirzad,99386,35.77,53.35,1969.00
659,OIZH,Sistan Va Baluchestan,Sarbaz,19974,26.64,61.26,902.00
660,OIZH,Sistan Va Baluchestan,Sarbaz,19975,26.63,61.27,880.00

In [12]:
all_dates = pd.date_range(df['date'].min(), df['date'].max(), freq='D')

n = 1

def reindex_station(station_df):
    global n
    print(f"{n}: Reindexing station {station_df['region_name'].iloc[0]} - {station_df['station_name'].iloc[0]} - {station_df['station_elevation'].iloc[0]} - {station_df['lat'].iloc[0]} - {station_df['lon'].iloc[0]}")
    # print(station_df)
    n += 1
    return station_df.drop_duplicates('date').set_index('date').reindex(all_dates).assign(
        region_id=station_df['region_id'].iloc[0],
        region_name=station_df['region_name'].iloc[0],
        station_id=station_df['station_id'].iloc[0],
        station_name=station_df['station_name'].iloc[0],
        station_elevation=station_df['station_elevation'].iloc[0],
        lat=station_df['lat'].iloc[0],
        lon=station_df['lon'].iloc[0],
    ).reset_index().rename(columns={'index': 'date'})

df = (
    df.groupby(['region_id', 'region_name', 'station_id', 'station_name'], group_keys=False)
    .apply(reindex_station)
    .reset_index(drop=True)
)

1: Reindexing station Alborz - Zidashte Taleghan - 2255.0 - 36.13 - 50.68
2: Reindexing station Alborz - Asara - 1864.0 - 36.04 - 51.19
3: Reindexing station Alborz - Dizin Bala - 3328.0 - 36.035 - 51.434
4: Reindexing station Alborz - Pistechamandizin - 2692.0 - 36.05 - 51.42
5: Reindexing station Alborz - Shahrestanak - 2200.0 - 35.971 - 51.357
6: Reindexing station Alborz - Shahrak Sanati Daroii Barakat - 1455.0 - 35.919 - 50.856
7: Reindexing station Alborz - Piste Khur - 2415.0 - 35.914 - 51.161
8: Reindexing station Alborz - Meshkin Dasht - 1289.0 - 35.76 - 50.96
9: Reindexing station Alborz - Eshtehard - 1191.0 - 35.72 - 50.37
10: Reindexing station Alborz - Karaj - 1292.9 - 35.807 - 50.954
11: Reindexing station Alborz - Kandoovan Jonobi - 2583.0 - 36.13 - 51.32
12: Reindexing station Alborz - Payam Airport - 1259.8 - 35.765 - 50.84
13: Reindexing station Alborz - Nazarabad - 1168.0 - 35.933 - 50.55
14: Reindexing station Alborz - Taleghan - 1857.0 - 36.18 - 50.77
15: Reindexing station Alborz - Karaj (Agricultural) - 1261.1 - 35.78 - 50.938
16: Reindexing station Alborz - Hashtgerd - 1612.9 - 36.006 - 50.747
17: Reindexing station Markazi - Aveh - 1000.0 - 34.804953 - 50.376823
18: Reindexing station Markazi - Varin Bala - 1808.0 - 34.034302 - 50.372127
19: Reindexing station Markazi - Amanabad - 1728.0 - 34.005 - 49.928
20: Reindexing station Markazi - Arak - 1702.8 - 34.07 - 49.78
21: Reindexing station Markazi - Mahallat - 1622.0 - 33.89 - 50.48
22: Reindexing station Markazi - Arak (Airport) - 1661.9 - 34.133 - 49.84
23: Reindexing station Markazi - Saveh - 1111.6 - 35.08 - 50.37
24: Reindexing station Markazi - Zarandieh - 0.0 - 35.3 - 50.47
25: Reindexing station Markazi - Tafresh - 1979.7 - 34.684 - 50.037
26: Reindexing station Markazi - Ashtiyan - 2097.0 - 34.519 - 50.012
27: Reindexing station Markazi - Gharqabad - 1590.0 - 35.11 - 49.83
28: Reindexing station Markazi - Farahan-Supplementary Synoptic - 1784.0 - 34.497 - 49.693
29: Reindexing station Markazi - Komijan - 1741.0 - 34.71 - 49.31
30: Reindexing station Markazi - Khondab - 1739.0 - 34.41 - 49.18
31: Reindexing station Markazi - Shazand - 1913.0 - 33.94 - 49.41
32: Reindexing station Markazi - Khomeyn - 1834.6 - 33.62 - 50.07
33: Reindexing station Markazi - Delijan - 1524.3 - 33.98 - 50.69
34: Reindexing station Mazandaran - Tonekabon - 0.0 - 36.81 - 50.9
35: Reindexing station Mazandaran - Jouybar - -17.0 - 36.69139 - 52.89667
36: Reindexing station Mazandaran - Bisheh Bone - 1440.0 - 36.567 - 53.816
37: Reindexing station Mazandaran - Kelardasht - 1200.0 - 36.55 - 51.157
38: Reindexing station Mazandaran - Babolkenar - 91.0 - 36.35 - 52.717
39: Reindexing station Mazandaran - Dalir - 1995.0 - 36.32306 - 51.10194
40: Reindexing station Mazandaran - Shayadehband Pay - 213.0 - 36.317 - 52.553
41: Reindexing station Mazandaran - Ramsar - -20.0 - 36.905 - 50.684
42: Reindexing station Mazandaran - Nowshahr - -20.9 - 36.661 - 51.466
43: Reindexing station Mazandaran - Siahbisheh - 1855.4 - 36.231 - 51.303
44: Reindexing station Mazandaran - Babolsar - -21.0 - 36.699 - 52.643
45: Reindexing station Mazandaran - Gharakhil - 14.7 - 36.487 - 52.108
46: Reindexing station Mazandaran - Sari - 23.0 - 36.536 - 52.998
47: Reindexing station Mazandaran - Kiyasar - 1294.3 - 36.248 - 53.546
48: Reindexing station Mazandaran - Sari (Dasht-E-Naz Airport) - 16.7 - 36.64 - 53.195
49: Reindexing station Mazandaran - Galugah - -10.0 - 36.738 - 53.837
50: Reindexing station Mazandaran - Bandar-E-Amirabad - -20.0 - 36.856 - 53.386
51: Reindexing station Mazandaran - Izad Shahr - -26.0 - 36.609 - 52.16
52: Reindexing station Mazandaran - Amol - 23.7 - 36.479 - 52.468
53: Reindexing station Mazandaran - Rineh - 2130.0 - 35.879 - 52.154
54: Reindexing station Mazandaran - Kojur - 1550.0 - 36.39 - 51.729
55: Reindexing station Mazandaran - Baladeh - 2120.0 - 36.198 - 51.801
56: Reindexing station Mazandaran - Polsefid - 610.0 - 36.104 - 53.062
57: Reindexing station Mazandaran - Alasht - 1805.0 - 36.071 - 52.843
58: Reindexing station Khuzestan - Baghmalek - 710.0 - 31.53 - 49.88
59: Reindexing station Khuzestan - Hovizeh - 13.0 - 31.472 - 48.083
60: Reindexing station Khuzestan - Haftgel - 285.0 - 31.435833 - 49.524167
61: Reindexing station Khuzestan - Ramshir - 26.0 - 30.920556 - 49.431667
62: Reindexing station Khuzestan - Safiabad (Dezful) - 82.9 - 32.253 - 48.433
63: Reindexing station Khuzestan - Dezful (Airport) - 143.0 - 32.3994 - 48.3831
64: Reindexing station Khuzestan - Bostan - 7.8 - 31.708 - 48.01
65: Reindexing station Khuzestan - Ahvaz - 22.5 - 31.344 - 48.744
66: Reindexing station Khuzestan - Masjedsoleyman - 320.5 - 31.983 - 49.241
67: Reindexing station Khuzestan - Ramhormoz - 150.5 - 31.273 - 49.596
68: Reindexing station Khuzestan - Omidiyeh (Air Base) - 34.9 - 30.8342 - 49.5467
69: Reindexing station Khuzestan - Abadan - 6.6 - 30.37 - 48.22
70: Reindexing station Khuzestan - Bandar-E- Mahshahr - 6.2 - 30.546 - 49.159
71: Reindexing station Khuzestan - Omidiyeh (Aghajari) - 27.0 - 30.743 - 49.688
72: Reindexing station Khuzestan - Behbahan - 313.0 - 30.606 - 50.217
73: Reindexing station Khuzestan - Shushtar - 67.0 - 32.05 - 48.833
74: Reindexing station Khuzestan - Izeh - 767.0 - 31.848 - 49.854
75: Reindexing station Khuzestan - Shadegan - 3.0 - 30.657 - 48.642
76: Reindexing station Khuzestan - Hoseyniyeh - 354.0 - 32.67 - 48.254
77: Reindexing station Khuzestan - Lali - 365.0 - 32.336 - 49.1
78: Reindexing station Khuzestan - Gotvand - 70.0 - 32.223 - 48.809
79: Reindexing station Khuzestan - Shush - 65.0 - 32.194 - 48.239
80: Reindexing station Khuzestan - Dehdez - 1457.0 - 31.708 - 50.281
81: Reindexing station Khuzestan - Ahvaz (Agricultural) - 12.0 - 31.25 - 48.55
82: Reindexing station Khuzestan - Hendijan - 3.0 - 30.249 - 49.706
83: Reindexing station Khuzestan - Aghajari - 143.0 - 30.7 - 49.83
84: Reindexing station Bushehr - Abpakhsh - 46.0 - 29.35 - 51.06
85: Reindexing station Bushehr - Shabankareh - 35.0 - 29.81 - 50.59
86: Reindexing station Bushehr - Tang E Eram - 890.0 - 29.15 - 51.53
87: Reindexing station Bushehr - Borazjan University Agricultuire - 92.0 - 29.2166 - 51.2333
88: Reindexing station Bushehr - Chahkootah (Tasbit E Shen) - 30.0 - 29.03 - 51.09
89: Reindexing station Bushehr - Khormooj - 71.0 - 28.66111 - 51.38333
90: Reindexing station Bushehr - Bandar Ameri - 7.0 - 28.513 - 51.093
91: Reindexing station Bushehr - Ahram - 57.0 - 28.88 - 51.27
92: Reindexing station Bushehr - Bordekhoon - 12.0 - 28.03 - 51.45
93: Reindexing station Bushehr - Dareban Riz - 373.0 - 28.029 - 52.117
94: Reindexing station Bushehr - Kangan - 8.0 - 27.8333 - 52.0667
95: Reindexing station Bushehr - Khark Island - 5.0 - 29.265 - 50.315
96: Reindexing station Bushehr - Bandar-E-Deylam - 3.9 - 30.05 - 50.17
97: Reindexing station Bushehr - Bushehr (Coastal) - 8.4 - 28.904 - 50.821
98: Reindexing station Bushehr - Bushehr (Airport) - 9.0 - 28.96 - 50.82
99: Reindexing station Bushehr - Bandar-E-Dayyer - 4.0 - 27.83 - 51.93
100: Reindexing station Bushehr - Behregan - 1432.0 - 29.838 - 50.272
101: Reindexing station Bushehr - Jam - 659.0 - 27.816 - 52.356
102: Reindexing station Bushehr - Asaluyeh (Airport) - 7.0 - 27.48 - 52.62
103: Reindexing station Bushehr - Bandar-E-Genaveh - 4.3 - 29.56 - 50.51
104: Reindexing station Bushehr - Borazjan - 89.9 - 29.27 - 51.22
105: Reindexing station Kermanshah - Paveh - 1494.0 - 35.03 - 46.33
106: Reindexing station Kermanshah - Dinavar - 1370.0 - 34.5835 - 47.4462
107: Reindexing station Kermanshah - Kivehnan - 1970.0 - 35.367 - 47.3
108: Reindexing station Kermanshah - Koozaran - 1380.0 - 34.33 - 46.6
109: Reindexing station Kermanshah - Sahneh - 1382.0 - 34.47 - 47.7
110: Reindexing station Kermanshah - Beeseton - 2038.0 - 34.39 - 47.44
111: Reindexing station Kermanshah - Khosravi - 283.0 - 34.383 - 45.533
112: Reindexing station Kermanshah - Gahvareh - 1520.0 - 34.33 - 46.42
113: Reindexing station Kermanshah - Mahidasht(Robat) - 1370.0 - 34.28 - 46.85
114: Reindexing station Kermanshah - Kerend Gharb - 1530.0 - 34.28 - 46.23
115: Reindexing station Kermanshah - Halashi - 1785.0 - 34.1 - 47.08
116: Reindexing station Kermanshah - Sarmast - 1476.0 - 34.0167 - 46.33333
117: Reindexing station Kermanshah - Homil - 1320.0 - 33.92 - 46.77
118: Reindexing station Kermanshah - Ravansar - 1380.0 - 34.71 - 46.65
119: Reindexing station Kermanshah - Sarpol-E-Zahab - 545.0 - 34.45 - 45.86
120: Reindexing station Kermanshah - Kermanshah - 1318.5 - 34.352 - 47.153
121: Reindexing station Kermanshah - Kangavar - 1468.0 - 34.5 - 47.98
122: Reindexing station Kermanshah - Eslamabad-E-Gharb - 1348.8 - 34.12 - 46.47
123: Reindexing station Kermanshah - Javanrud - 1375.4 - 34.76 - 46.5
124: Reindexing station Kermanshah - Tazehabad (Kermanshah) - 1226.0 - 34.75 - 46.15
125: Reindexing station Kermanshah - Sonqor - 1700.0 - 34.78 - 47.58
126: Reindexing station Kermanshah - Sumar - 297.0 - 33.88 - 45.65
127: Reindexing station Kermanshah - Harsin - 1546.0 - 34.26 - 47.55
128: Reindexing station Kermanshah - Qasreshirin - 375.9 - 34.52 - 45.6
129: Reindexing station Kermanshah - Gilanegharb - 816.3 - 34.13 - 45.93
130: Reindexing station Kermanshah - Sararud (Kermanshah) - 1361.7 - 34.33 - 47.29
131: Reindexing station Ilam - Holeylan - 870.0 - 33.72583 - 47.07028
132: Reindexing station Ilam - Blavetareh - 900.0 - 33.667 - 46.806
133: Reindexing station Ilam - Malekshahi - 1432.0 - 33.41 - 46.6
134: Reindexing station Ilam - Badreh - 1062.0 - 33.306 - 47.033
135: Reindexing station Ilam - Ilam - 1337.0 - 33.588 - 46.398
136: Reindexing station Ilam - Mehran - 150.0 - 33.115 - 46.176
137: Reindexing station Ilam - Dehloran - 232.0 - 32.681 - 47.281
138: Reindexing station Ilam - Darrehshahr - 670.0 - 33.137 - 47.408
139: Reindexing station Ilam - Eyvan - 1290.0 - 33.763 - 46.36
140: Reindexing station Ilam - Loumar - 850.0 - 33.56 - 46.829
141: Reindexing station Ilam - Sarableh - 1045.0 - 33.792 - 46.579
142: Reindexing station Ilam - Abdanan - 920.0 - 32.996 - 47.423
143: Reindexing station Lorestan - Rymaleh - 1650.0 - 33.638 - 48.403
144: Reindexing station Lorestan - Iman Abad - 1595.0 - 33.369 - 48.606
145: Reindexing station Lorestan - Nurabad (Lorestan) - 1859.0 - 34.042 - 48.004
146: Reindexing station Lorestan - Borujerd - 1629.0 - 33.915 - 48.758
147: Reindexing station Lorestan - Alashtar - 1567.1 - 33.824 - 48.245
148: Reindexing station Lorestan - Khorramabad - 1147.8 - 33.433 - 48.295
149: Reindexing station Lorestan - Aligudarz - 2022.1 - 33.408 - 49.703
150: Reindexing station Lorestan - Poldokhtar - 713.5 - 33.155 - 47.719
151: Reindexing station Lorestan - Kuhdasht - 1197.8 - 33.524 - 47.648
152: Reindexing station Lorestan - Dorud - 1522.3 - 33.524 - 49.004
153: Reindexing station Lorestan - Azna - 1871.8 - 33.447 - 49.408
154: Reindexing station Lorestan - Silakhur - 1496.9 - 33.735 - 48.869
155: Reindexing station Lorestan - Rymaleh - 1650.0 - 33.6375 - 48.40333333
156: Reindexing station Lorestan - Romeshkan - 1089.0 - 33.287 - 47.505
157: Reindexing station Lorestan - Badrabad (Lorestan) - 1154.8 - 33.43388889 - 48.27944444
158: Reindexing station Lorestan - Imanabad - 1500.0 - 33.4 - 48.36666667
159: Reindexing station Lorestan - Sepiddasht - 1021.0 - 33.217 - 48.884
160: Reindexing station Lorestan - Shulabad - 1591.0 - 33.185 - 49.192
161: Reindexing station Kordestan - Baghlojeh - 1520.0 - 36.409 - 46.239
162: Reindexing station Kordestan - Goltappeh - 1657.0 - 36.36 - 46.67
163: Reindexing station Kordestan - Yasokansd - 1760.0 - 36.28 - 47.75
164: Reindexing station Kordestan - Baleh Jar - 1625.0 - 36.182 - 46.753
165: Reindexing station Kordestan - Haji Mamdan - 1826.0 - 35.95 - 46.35
166: Reindexing station Kordestan - Nesareh - 1755.0 - 35.87 - 47.07
167: Reindexing station Kordestan - Baba Reshani - 1662.0 - 35.67 - 47.79
168: Reindexing station Kordestan - Baharestan - 2070.0 - 35.67 - 47.12
169: Reindexing station Kordestan - Sarab Shahrak - 1983.0 - 35.6255 - 47.3575
170: Reindexing station Kordestan - Bakhan - 1484.0 - 35.533 - 46.378
171: Reindexing station Kordestan - Sarvabad - 1200.0 - 35.29 - 46.37
172: Reindexing station Kordestan - Dehgolan - 1815.0 - 35.28 - 47.42
173: Reindexing station Kordestan - Avihang - 1630.0 - 35.25 - 46.68
174: Reindexing station Kordestan - Selen - 936.0 - 35.23 - 46.32
175: Reindexing station Kordestan - Ghamloo - 1910.0 - 35.18 - 47.49
176: Reindexing station Kordestan - Moochesh - 1640.0 - 35.06 - 47.15
177: Reindexing station Kordestan - Saqez - 1522.8 - 36.221 - 46.311
178: Reindexing station Kordestan - Sanandaj - 1373.4 - 35.255 - 47.015
179: Reindexing station Kordestan - Bijar - 1883.4 - 35.886 - 47.621
180: Reindexing station Kordestan - Zarrineh - 2142.6 - 36.06 - 46.914
181: Reindexing station Kordestan - Marivan - 1287.0 - 35.497 - 46.152
182: Reindexing station Kordestan - Qorveh - 1906.0 - 35.18 - 47.786
183: Reindexing station Kordestan - Baneh - 1600.0 - 36.007 - 45.895
184: Reindexing station Kordestan - Hezarkaniyan - 1934.0 - 35.765 - 46.812
185: Reindexing station Kordestan - Kamyaran - 1404.0 - 34.788 - 46.894
186: Reindexing station Esfahan - Dehaghan - 2060.0 - 31.935 - 51.635
187: Reindexing station Esfahan - Foolad Mobarakeh - 1830.0 - 32.231 - 51.416
188: Reindexing station Esfahan - Aran Va Bidgol - 934.0 - 34.04 - 51.466
189: Reindexing station Esfahan - Barzook - 1950.0 - 33.78 - 51.223
190: Reindexing station Esfahan - Jangalbani- Badroud Natanz - 1056.0 - 33.684 - 52.015
191: Reindexing station Esfahan - Mahaabad - 995.0 - 33.517 - 52.219
192: Reindexing station Esfahan - Zavareh - 0.0 - 33.44 - 52.473
193: Reindexing station Esfahan - Anarak - 1645.0 - 33.309 - 53.693
194: Reindexing station Esfahan - Bayaze - 920.0 - 33.3375 - 55.098889
195: Reindexing station Esfahan - Eslamabadmogoyee - 2449.0 - 33.021 - 49.819
196: Reindexing station Esfahan - Booin Va Miyandasht - 2412.0 - 33.077 - 50.168
197: Reindexing station Esfahan - Hesa - 2449.0 - 32.9167 - 51.55
198: Reindexing station Esfahan - Asgaran - 2135.0 - 32.873 - 50.851
199: Reindexing station Esfahan - Dolat Abad Borkhar - 1560.0 - 32.812 - 51.703
200: Reindexing station Esfahan - Kohpaye - 1805.0 - 32.717 - 52.452
201: Reindexing station Esfahan - Palayeshgah Esfahan - 1673.0 - 32.774 - 51.507
202: Reindexing station Esfahan - Harand - 1556.0 - 32.5731 - 52.4372
203: Reindexing station Esfahan - Tahghighate Keshavarzi Roodasht - 1510.0 - 32.493 - 52.189
204: Reindexing station Esfahan - Bide - 2307.0 - 30.934 - 51.687
205: Reindexing station Esfahan - Kashan - 955.0 - 33.967 - 51.48
206: Reindexing station Esfahan - Daran - 2290.0 - 32.988 - 50.407
207: Reindexing station Esfahan - Khur-Va-Biabanak - 842.2 - 33.77 - 55.081
208: Reindexing station Esfahan - Ardestan - 1255.5 - 33.355 - 52.376
209: Reindexing station Esfahan - Esfahan - 1550.4 - 32.518 - 51.707
210: Reindexing station Esfahan - Naein - 1573.7 - 32.851 - 53.079
211: Reindexing station Esfahan - Esfahan (Airport) - 1551.9 - 32.493 - 51.863
212: Reindexing station Esfahan - Kabutarabad - 1542.5 - 32.515 - 51.834
213: Reindexing station Esfahan - Shahreza - 1858.0 - 31.982 - 51.81
214: Reindexing station Esfahan - Golpayegan - 1870.0 - 33.477 - 50.261
215: Reindexing station Esfahan - Natanz - 1685.0 - 33.49 - 51.931
216: Reindexing station Esfahan - Meymeh - 1980.0 - 33.452 - 51.175
217: Reindexing station Esfahan - Murchehkhort - 1673.0 - 33.079 - 51.481
218: Reindexing station Esfahan - Chadegan - 2175.0 - 32.757 - 50.65
219: Reindexing station Esfahan - Chupanan - 896.3 - 33.611 - 54.379
220: Reindexing station Esfahan - Khansar - 2300.0 - 33.209 - 50.322
221: Reindexing station Esfahan - Dehagh - 1946.7 - 33.097 - 50.975
222: Reindexing station Esfahan - Fereidunshahr - 2490.0 - 32.94 - 50.127
223: Reindexing station Esfahan - Sanati Esfahan - 1626.0 - 32.71416667 - 51.53444444
224: Reindexing station Esfahan - Najafabad - 1636.2 - 32.604 - 51.389
225: Reindexing station Esfahan - Varzaneh - 1450.0 - 32.433 - 52.617
226: Reindexing station Esfahan - Mobarakeh - 1680.2 - 32.359 - 51.451
227: Reindexing station Esfahan - Zarrinshahr - 1713.8 - 32.399 - 51.378
228: Reindexing station Esfahan - Samirom - 2459.9 - 31.418 - 51.549
229: Reindexing station Chaharmahal Va Bakhtiari - Lirabi - 1948.0 - 31.958 - 50.485
230: Reindexing station Chaharmahal Va Bakhtiari - Ben - 2228.0 - 32.54 - 50.74
231: Reindexing station Chaharmahal Va Bakhtiari - Soodejan - 1971.0 - 32.514 - 50.04
232: Reindexing station Chaharmahal Va Bakhtiari - Sooreshjan - 2130.0 - 32.32 - 50.69
233: Reindexing station Chaharmahal Va Bakhtiari - Dashtak - 2322.0 - 32.161 - 50.469
234: Reindexing station Chaharmahal Va Bakhtiari - Doab Samsami - 2064.0 - 32.17 - 50.29
235: Reindexing station Chaharmahal Va Bakhtiari - Bazoft - 1490.0 - 32.211 - 50.033
236: Reindexing station Chaharmahal Va Bakhtiari - Adl Dezak - 2054.0 - 32.083 - 50.95
237: Reindexing station Chaharmahal Va Bakhtiari - Shalamzar - 2041.0 - 32.04 - 50.82
238: Reindexing station Chaharmahal Va Bakhtiari - Emam Ghaes - 2195.0 - 31.75483 - 51.30719
239: Reindexing station Chaharmahal Va Bakhtiari - Aloni - 1750.0 - 31.55667 - 51.06278
240: Reindexing station Chaharmahal Va Bakhtiari - Sarkhoon - 1469.0 - 31.729166 - 50.574444
241: Reindexing station Chaharmahal Va Bakhtiari - Mal Khalifeh - 1762.0 - 31.28 - 51.25
242: Reindexing station Chaharmahal Va Bakhtiari - Kuhrang - 2365.0 - 32.458 - 50.125
243: Reindexing station Chaharmahal Va Bakhtiari - Shahrekord - 2048.9 - 32.293 - 50.84
244: Reindexing station Chaharmahal Va Bakhtiari - Lordegan - 1611.0 - 31.503 - 50.833
245: Reindexing station Chaharmahal Va Bakhtiari - Borujen - 2260.0 - 31.979 - 51.299
246: Reindexing station Chaharmahal Va Bakhtiari - Ilbagi ( Pole Zamankhan) - 1883.0 - 32.5 - 50.895
247: Reindexing station Chaharmahal Va Bakhtiari - Saman - 2075.0 - 32.437 - 50.875
248: Reindexing station Chaharmahal Va Bakhtiari - Farokhshahr - 2085.0 - 32.298 - 50.931
249: Reindexing station Chaharmahal Va Bakhtiari - Farsan - 2062.0 - 32.275 - 50.565
250: Reindexing station Chaharmahal Va Bakhtiari - Ardal - 1873.0 - 32.013 - 50.663
251: Reindexing station Chaharmahal Va Bakhtiari - Boldaji - 0.0 - 31.931 - 51.061
252: Reindexing station Gilan - Hyran - 25.0 - 38.4 - 48.604
253: Reindexing station Gilan - Lisar - -24.0 - 37.992 - 48.921
254: Reindexing station Gilan - Asbehboni - 1610.0 - 37.62 - 48.77
255: Reindexing station Gilan - Pelimbara - 6.0 - 37.6 - 49.07
256: Reindexing station Gilan - Rezvanshahr - -26.0 - 37.567 - 49.19
257: Reindexing station Gilan - Roshandeh - 1188.0 - 37.5269 - 48.8705
258: Reindexing station Gilan - Abkenar - 9.0 - 37.45667 - 49.32361
259: Reindexing station Gilan - Masal - 63.0 - 37.356 - 49.126
260: Reindexing station Gilan - Somehsara - 1.0 - 37.283 - 49.329
261: Reindexing station Gilan - Astane Ashrafiye - -20.0 - 37.29 - 49.93
262: Reindexing station Gilan - Toton Rasht - 30.0 - 37.2705 - 49.5212
263: Reindexing station Gilan - Fooman - 42.0 - 37.23 - 49.32
264: Reindexing station Gilan - Langrod - -22.0 - 37.18 - 50.15
265: Reindexing station Gilan - Azberam - 50.0 - 37.14 - 49.92
266: Reindexing station Gilan - Amlash - 40.0 - 37.1 - 50.17
267: Reindexing station Gilan - Emamzadeh Eshagh - 1009.0 - 37.053 - 49.325
268: Reindexing station Gilan - Baresar - 1185.0 - 36.7725 - 49.74525
269: Reindexing station Gilan - Loshan - 550.0 - 36.62 - 49.52
270: Reindexing station Gilan - Jirkol - 498.0 - 36.051 - 50.234
271: Reindexing station Gilan - Astara - -21.1 - 38.365 - 48.855
272: Reindexing station Gilan - Bandar-E-Anzali - -23.6 - 37.48 - 49.458
273: Reindexing station Gilan - Rasht - -8.6 - 37.323 - 49.624
274: Reindexing station Gilan - Manjil - 338.3 - 36.729 - 49.41
275: Reindexing station Gilan - Jirandeh - 1581.4 - 36.708 - 49.802
276: Reindexing station Gilan - Larzareh - 1964.0 - 37.6 - 48.71
277: Reindexing station Gilan - Talesh - 7.0 - 37.839 - 48.897

In [13]:
df

,date,station_id,station_name,region_id,region_name,lat,lon,station_elevation,tmax,tmin,tm,umax,umin,um,ffm,sshn,rrr24,pm,p0m,ewm,radglo24,evt,td_m,twet_m,tsoil_m,ewsm
0,1951-01-01 12:00:00,18554,Zidashte Taleghan,ALKK,Alborz,36.13,50.68,2255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1951-01-02 12:00:00,18554,Zidashte Taleghan,ALKK,Alborz,36.13,50.68,2255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1951-01-03 12:00:00,18554,Zidashte Taleghan,ALKK,Alborz,36.13,50.68,2255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1951-01-04 12:00:00,18554,Zidashte Taleghan,ALKK,Alborz,36.13,50.68,2255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1951-01-05 12:00:00,18554,Zidashte Taleghan,ALKK,Alborz,36.13,50.68,2255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21097484,2025-09-17 12:00:00,99440,Kahak,QOQM,Qom,34.40,50.87,1403.10,31.40,16.90,24.10,41.00,18.00,26.17,3.17,10.70,0.00,1005.84,858.92,7.92,2348.00,10.40,3.42,13.44,16.00,31.74
21097485,2025-09-18 12:00:00,99440,Kahak,QOQM,Qom,34.40,50.87,1403.10,30.90,16.70,23.80,33.00,18.00,24.25,3.25,10.80,0.00,1005.85,858.89,7.56,2351.00,9.90,2.72,13.30,15.00,31.94
21097486,2025-09-19 12:00:00,99440,Kahak,QOQM,Qom,34.40,50.87,1403.10,35.70,17.50,26.60,28.00,8.00,17.70,3.13,10.00,0.00,1000.59,855.40,6.28,2247.00,10.40,0.25,13.68,16.00,38.07
21097487,2025-09-20 12:00:00,99440,Kahak,QOQM,Qom,34.40,50.87,1403.10,32.60,19.40,26.00,27.00,5.00,18.00,3.14,11.00,0.00,1000.94,855.31,5.15,2341.00,10.60,-3.18,11.51,16.00,31.17
21097488,2025-09-21 12:00:00,99440,Kahak,QOQM,Qom,34.40,50.87,1403.10,27.10,14.70,20.90,29.00,19.00,23.46,3.67,9.90,0.00,1005.80,857.32,5.84,2234.00,10.90,-0.74,10.69,13.00,25.68

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21097489 entries, 0 to 21097488
Data columns (total 26 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[ns]
 1   station_id         object
 2   station_name       object
 3   region_id          object
 4   region_name        object
 5   lat                float64
 6   lon                float64
 7   station_elevation  float64
 8   tmax               float64
 9   tmin               float64
 10  tm                 float64
 11  umax               float64
 12  umin               float64
 13  um                 float64
 14  ffm                float64
 15  sshn               float64
 16  rrr24              float64
 17  pm                 float64
 18  p0m                float64
 19  ewm                float64
 20  radglo24           float64
 21  evt                float64
 22  td_m               float64
 23  twet_m             float64
 24  tsoil_m            float64
 25  ewsm               float64
dtypes: datetime64[ns](1), float64(21), object(4)
memory usage: 4.1+ GB

In [15]:
all_dates

DatetimeIndex(['1951-01-01 12:00:00', '1951-01-02 12:00:00',
               '1951-01-03 12:00:00', '1951-01-04 12:00:00',
               '1951-01-05 12:00:00', '1951-01-06 12:00:00',
               '1951-01-07 12:00:00', '1951-01-08 12:00:00',
               '1951-01-09 12:00:00', '1951-01-10 12:00:00',
               ...
               '2025-09-12 12:00:00', '2025-09-13 12:00:00',
               '2025-09-14 12:00:00', '2025-09-15 12:00:00',
               '2025-09-16 12:00:00', '2025-09-17 12:00:00',
               '2025-09-18 12:00:00', '2025-09-19 12:00:00',
               '2025-09-20 12:00:00', '2025-09-21 12:00:00'],
              dtype='datetime64[ns]', length=27293, freq='D')

# Export Daily Data

In [16]:
# # To pickle in data folder
# with open('../../data/Iran_Daily_Data_1951_2025.pkl', 'wb') as f:
#     pickle.dump(df, f)

# To parquet in data folder
df.to_parquet('../../data/Iran_Daily_Data_1951_2025.parquet', index=False)

# Monthly Data

In [17]:

# generate monthly data all mean exept rrr24 sum, and count of days for each month and variable not NA
df["year"] = df['date'].dt.year
df["month"] = df['date'].dt.month

df_monthly = df.groupby(['year', 'month', 'region_id', 'region_name', 'station_id', 'station_name']).agg({
    'lat': 'first',
    'lon': 'first',
    'station_elevation': 'first',
    'tmax': ['mean', 'count'],
    'tmin': ['mean', 'count'], 
    'tm': ['mean', 'count'],
    'umax': ['mean', 'count'],
    'umin': ['mean', 'count'],
    'um': ['mean', 'count'],
    'ffm': ['mean', 'count'],
    'sshn': ['mean', 'count'],
    'pm': ['mean', 'count'],
    'p0m': ['mean', 'count'],
    'ewm': ['mean', 'count'],
    'radglo24': ['mean', 'count'],
    'td_m': ['mean', 'count'],
    'twet_m': ['mean', 'count'],
    'tsoil_m': ['mean', 'count'],
    'ewsm': ['mean', 'count'],
    'evt': ['sum', 'count'],
    'rrr24': ['sum', 'count']
}).reset_index()

df_monthly.columns = ['_'.join(col).strip() if col[1] else col[0] for col in df_monthly.columns.values]
df_monthly.rename(columns=lambda x: x.replace('_mean', '').replace('_sum', '').replace('_first', ''), inplace=True)
df_monthly = df_monthly.round(2)
df_monthly.sort_values(by=['region_name', 'station_name', 'station_id', 'year', 'month'], inplace=True)
df_monthly.reset_index(drop=True, inplace=True)

In [18]:
df_monthly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693381 entries, 0 to 693380
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   year               693381 non-null  int32
 1   month              693381 non-null  int32
 2   region_id          693381 non-null  object
 3   region_name        693381 non-null  object
 4   station_id         693381 non-null  object
 5   station_name       693381 non-null  object
 6   lat                693381 non-null  float64
 7   lon                693381 non-null  float64
 8   station_elevation  693381 non-null  float64
 9   tmax               162557 non-null  float64
 10  tmax_count         693381 non-null  int64
 11  tmin               161808 non-null  float64
 12  tmin_count         693381 non-null  int64
 13  tm                 161595 non-null  float64
 14  tm_count           693381 non-null  int64
 15  umax               136818 non-null  float64
 16  umax_count         693381 non-null  int64
 17  umin               136818 non-null  float64
 18  umin_count         693381 non-null  int64
 19  um                 136818 non-null  float64
 20  um_count           693381 non-null  int64
 21  ffm                138913 non-null  float64
 22  ffm_count          693381 non-null  int64
 23  sshn               108040 non-null  float64
 24  sshn_count         693381 non-null  int64
 25  pm                 136544 non-null  float64
 26  pm_count           693381 non-null  int64
 27  p0m                137012 non-null  float64
 28  p0m_count          693381 non-null  int64
 29  ewm                136582 non-null  float64
 30  ewm_count          693381 non-null  int64
 31  radglo24           23204 non-null   float64
 32  radglo24_count     693381 non-null  int64
 33  td_m               137216 non-null  float64
 34  td_m_count         693381 non-null  int64
 35  twet_m             138451 non-null  float64
 36  twet_m_count       693381 non-null  int64
 37  tsoil_m            128407 non-null  float64
 38  tsoil_m_count      693381 non-null  int64
 39  ewsm               139011 non-null  float64
 40  ewsm_count         693381 non-null  int64
 41  evt                693381 non-null  float64
 42  evt_count          693381 non-null  int64
 43  rrr24              693381 non-null  float64
 44  rrr24_count        693381 non-null  int64
dtypes: float64(21), int32(2), int64(18), object(4)
memory usage: 232.8+ MB

# Export Monthly Data

In [19]:
# # To pickle in data folder
# with open('../../data/Iran_Monthly_Data_1951_2025.pkl', 'wb') as f:
#     pickle.dump(df_monthly, f)

# To parquet in data folder
df_monthly.to_parquet('../../data/Iran_Monthly_Data_1951_2025.parquet', index=False)