# Load Libraries

In [1]:
import os
import warnings
import logging
import sys
import pickle
import numpy as np
import pandas as pd
import geopandas as gpd
import dotenv
import pyet
import matplotlib.pyplot as plt


# Load environment variables from .env file
dotenv.load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)

# Suppress warnings
warnings.filterwarnings("ignore")

# Set display options for pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_colwidth', None)

# Load Data

In [2]:
# Load Data From Pickle
with open('../../data/Iran_Monthly_ETo_1951_2025.pkl', 'rb') as f:
    data = pickle.load(f)
    logging.info("Data loaded from pickle file.")

INFO:root:Data loaded from pickle file.

In [3]:
data

,year,month,region_id,region_name,station_id,station_name,lat,lon,station_elevation,tmax,tmax_count,tmin,tmin_count,tm,tm_count,umax,umax_count,umin,umin_count,um,um_count,ffm,ffm_count,sshn,sshn_count,rrr24,rrr24_count,date,FAO56,Hargreaves,Blaney_Criddle,Oudin
0,1951,1,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,1951-01-01,NaN,NaN,NaN,NaN
1,1951,2,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,1951-02-01,NaN,NaN,NaN,NaN
2,1951,3,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,1951-03-01,NaN,NaN,NaN,NaN
3,1951,4,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,1951-04-01,NaN,NaN,NaN,NaN
4,1951,5,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,1951-05-01,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694273,2025,5,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,24.46,13,12.53,10,19.07,10,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,12.20,11,2025-05-01,NaN,147.74,110.63,121.41
694274,2025,6,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,32.03,30,12.43,28,22.12,28,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,29,2025-06-01,NaN,207.46,125.91,138.41
694275,2025,7,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,36.54,31,17.80,30,27.14,30,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,3.10,30,2025-07-01,NaN,232.24,149.49,166.81
694276,2025,8,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,37.20,20,19.91,11,29.04,11,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,19,2025-08-01,NaN,213.22,145.58,162.03
694277,2025,9,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,31.60,2,17.90,1,23.75,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,1,2025-09-01,NaN,136.65,105.47,111.07

In [7]:
data = data[[
    'region_id', 'region_name', 'station_id', 'station_name',
    'lat', 'lon', 'station_elevation',
    'date', 'year', 'month',
    'tmax', 'tmax_count', 'tmin', 'tmin_count', 'tm', 'tm_count', 
    'umax', 'umax_count', 'umin', 'umin_count', 'um', 'um_count',
    'ffm', 'ffm_count', 'sshn', 'sshn_count', 'rrr24', 'rrr24_count',
    'FAO56', 'Hargreaves', 'Blaney_Criddle', 'Oudin'
]]

data

,region_id,region_name,station_id,station_name,lat,lon,station_elevation,date,year,month,tmax,tmax_count,tmin,tmin_count,tm,tm_count,umax,umax_count,umin,umin_count,um,um_count,ffm,ffm_count,sshn,sshn_count,rrr24,rrr24_count,FAO56,Hargreaves,Blaney_Criddle,Oudin
0,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,1951-01-01,1951,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,NaN,NaN,NaN,NaN
1,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,1951-02-01,1951,2,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,NaN,NaN,NaN,NaN
2,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,1951-03-01,1951,3,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,NaN,NaN,NaN,NaN
3,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,1951-04-01,1951,4,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,NaN,NaN,NaN,NaN
4,OIID,Airforce,40753,Dowshan Tappeh,35.70,51.48,1209.20,1951-05-01,1951,5,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694273,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,2025-05-01,2025,5,24.46,13,12.53,10,19.07,10,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,12.20,11,NaN,147.74,110.63,121.41
694274,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,2025-06-01,2025,6,32.03,30,12.43,28,22.12,28,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,29,NaN,207.46,125.91,138.41
694275,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,2025-07-01,2025,7,36.54,31,17.80,30,27.14,30,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,3.10,30,NaN,232.24,149.49,166.81
694276,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,2025-08-01,2025,8,37.20,20,19.91,11,29.04,11,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,19,NaN,213.22,145.58,162.03
694277,OITZ,Zanjan,18699,Zarrenrood,35.75,48.48,1751.00,2025-09-01,2025,9,31.60,2,17.90,1,23.75,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0.00,1,NaN,136.65,105.47,111.07

In [13]:
data.FAO56.describe()

count   106734.00
mean       134.13
std         86.14
min          9.73
25%         59.34
50%        120.22
75%        195.62
max        701.41
Name: FAO56, dtype: float64